server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: patient-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-patient:5432/patient_db}
    username: ${SPRING_DATASOURCE_USERNAME:patient_user}
    password: ${SPRING_DATASOURCE_PASSWORD:change-this-password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.patientmanagement.patient: DEBUG
